### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by dookie23**
Hi,
 you are doing a great work with this tool!

I really love gitinspector and i would like to contribute with Spanish translation. I was working on spanish .mo & .po files on the basis of other existent translations. Please find attached below these files to include in source code if you want. 

Of course, i would be happy to generate new files to support Spanish translation in future releases.

Thank you for sharing the tool!

### CODE REVIEW

**Comment by adam-waldenberg** [comment]
Hi and thank you for the praise. It's nice to know that people find gitinspector useful.
I'll add you as the maintainer for the Spanish translation.

A couple of things need to be fixed before this pull request can be merged.

1. Add your name to the translation files (replace Phillipp Nowak).
2. Update PO-Revision-Date to the creation date of the translation.
3. The --help and --version texts should be targeted for a 80 character terminal and thus need to be updated a little. Also mind the formating of the help text which follows the convention of GNU tools. Just reference how the english help is printed out and try to achieve something similar.

**Comment by dookie23** [comment]
Hi Adam,
thank you for the instructions. I hope the files are valid now.

**Comment by adam-waldenberg** [comment]
Looks good. It's now added to master. I also took the liberty of squashing your branch.

**Comment by dookie23** [comment]
Thank you Adam!

I will be available for future updates.

**Comment by adam-waldenberg** [comment]
Hi. A new messages.pot has been added with commit 47b11ad, so an update is needed to the translation file. Refter to the commit diff to see all changes.

Once updated, the translation can be included in the upcoming 0.4.2 release.

**Comment by dookie23** [comment]
Hi Adam,

the Spanish translation is ready for release. I've just added the files in the last commit.

**Comment by adam-waldenberg** [comment]
Hi. The translation looks great. I'm nitpicking here, but could you please remove the reference to 0.4.2 from the commit message? That way I can just merge without rewriting the commit.

**Comment by dookie23** [comment]
Reference to 0.4.2 removed!

**Comment by adam-waldenberg** [comment]
Great. One more request; could you rebase your branch onto the master branch?

**Comment by dookie23** [comment]
Hello Adam,

I do not have much experience in rebasing. I ran "git rebase upstream/master" from my master branch . After that, I pull & push into my repository.

Could you please confirm everything is ok?

**Comment by adam-waldenberg** [comment]
Hi. Right now the pull request is asking for six commits to be merged.

If you do it right, you should be sync'ed up with the ejwa/gitinspector master branch, with your last commit on the top. Without any visible merges. A solution could be to move your master branch to a dev branch, sync up your master to gitinspector/master and just cherry pick the last commit from your dev to your master.

The reason I'm asking for the rebase is so that GitHub can register this pull request as merged; it won't do it if I for example, cherry pick the commit from your branch by myself, as that would change the hash and not include everything from this pull request.

**Comment by adam-waldenberg** [comment]
Hmm. Now that I look at the history I think the only way for GitHub to properly catch this pull request is to create a new one based on the new changes?

I'll just cherry pick your commit instead :). It's not worth the hassle.

**Comment by adam-waldenberg** [comment]
Done. Commited to the master branch with 9368898.

**Pull request closed without merging**
