### PR TITLE
Setup npm package

### PR DESCRIPTION
**Pull request by bartvanandel**
I've put some effort into turning this nice tool into an npm package. I've just published and tested it, works like a charm! Would you consider pulling the changes into master?

NB: I've added myself as a contributor for this, but I've set up the package to point to the original (your) github page, assuming you'd agree. If this is not desired, please let me know and I'll change it. If you'd like to be able to push to npm yourself, let me know as well so I can set this up.

### CODE REVIEW

**Comment by adam-waldenberg** [comment]
Hi @bartvanandel. Yes, we can add it to master. I personally don't use npm regularly , so it's better somebody else handles it. If you like, I can add you as the maintainer of this part.

**Comment by bartvanandel** [comment]
@adam-waldenberg, that sounds fine to me.

Note that I may have to update the package version number if a new npm release is required, at least in package.json. I'll try to keep those changes to a minimum.

**Comment by bartvanandel** [comment]
Any news about this pull request?

**Comment by adam-waldenberg** [comment]
Hi @bartvanandel . Will get to it as soon as I get time. In the future, I'll make sure to modify package.json when a new version is branhced. I'm planing a 0.4.4 release next. I'll let you handle the publishing when new versions get released.

**Comment by bartvanandel** [comment]
Okay, thanks, please inform me when the time is ripe.

**Comment by bartvanandel** [comment]
Changed a few things a few minutes ago.

- Fixed line ending issue (#142)
- Prefer global install
- Add a few keyword to help users find the npm package
- Shorten description a bit so it does not get truncated on npmjs.com

**Comment by adam-waldenberg** [comment]
@bartvanandel Officially merged in master. I'll let you know when I have 0.4.5 ready. I'm planning to have it ready for release relatively soon.

**Pull request merged**
