### PR TITLE
Update German translation for 0.4.3

### PR DESCRIPTION
**Pull request by xxyy**
This PR updates the German translation for the 0.4.3 release. Changes in translation include updating for changed messages in upstream and some rewording

Some translations have been changed to be more clear and to the point. Some comments have been added to messages that have been causing issues.

### CODE REVIEW

**Comment by adam-waldenberg** [comment]
Looks good! Thank you. I'll see if I can merge this tonight.

**Comment by adam-waldenberg** [comment]
Looks good. One minor request before I merge this; could you remove the reference to the 0.4.3 release from the commit message? This will be part of several branches when we release 0.4.3 and I want to keep the commit history clean with no references to any versions (bumps being the exception of course).

**Comment by xxyy** [comment]
Removed.

**Comment by adam-waldenberg** [comment]
Merged with commit bbe07f0. This will later be picked onto a release branch once I get enough new translations submitted for 0.4.3.

**Pull request closed without merging**
