### PR TITLE
Relative imports to fix packaging issues

### PR DESCRIPTION
**Pull request by marcharper**
Re: #73. Tested with Python 2.7.9 and 3.4.3.

### CODE REVIEW

**Comment by marcharper** [comment]
Should be good to go -- I tried to change as few lines as possible.

**Comment by adam-waldenberg** [comment]
Hi. Great! Thank you for taking the time to look into this.

I actually managed to "fix" this yesterday... But my solution was to change to absolute imports and moving gitinspector.py one level back.

This was the only way for me to get it to work without either breaking egg installations or being able to execute the script "locally"... It has to be said, I don't really like moving gitinspector.py to the root directory.

I'll look at your pull request tonight... It's probably be the better solution.

**Comment by marcharper** [comment]
This should work locally and doesn't require moving gitinspector.py. I tested actually installing and it works fine that way as well. Let me know if you have any questions or issues!

**Comment by adam-waldenberg** [comment]
Merged. After adding a new entry script to the root, this works fine.

**Pull request merged**
