### PR TITLE
fix some errors

### PR DESCRIPTION
**Pull request by bigplum**
Fix some errors with multiple projects,  if second project is empty:
1. The ref will not be initial.
2. Blame information will not shown.
3. Fix Nonetype in commits.

### CODE REVIEW

**Comment by adam-waldenberg** [comment]
Thank you. I actually think the NoneType in commits issue is related to the threading code.... I will investigate and merge your contribution once I have looked into it more.

**Comment by carera** [comment]
Checked this one out,
throws syntax error:

```
 File "/Users/minarikj/apps/gitinspector/gitinspector/changes.py", line 233
    else:
       ^
SyntaxError: invalid syntax
```

i guess the `else` expression is incorrectly indented

**Comment by bigplum** [comment]
It may caused by the spaces intent in my code.

**Comment by adam-waldenberg** [comment]
Going to take a look at this and also integrate parts of the pull request. A 0.4.5 release fixing this is most likely a good idea.

**Comment by adam-waldenberg** [comment]
This got fixed now I believe. Solved using a slightly different solution with better error handling.

The issue with NoneType in commits can still happen, as there is a bug in the threading code. I will look into this. When the threading code is fixed this should (theoretically) never occur.

Let me know if any of the other issues still persists.

**Pull request closed without merging**
